name: Deploy on Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          lua-version: '5.4'  # You can specify '5.1', '5.2', '5.3', '5.4', or 'luajit'

      - name: Install Lua canvas library
        run: |
          git clone https://github.com/wspr/canvas-lms-lua
          cd canvas-lms-lua
          luarocks make

      - name: Deploy
        run: |
          echo "Deploying release ${{ github.event.release.tag_name }}"
          make upload
        env:
          CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}
