name: Deploy and Release

on:
  push:
    tags:
      - "*"

jobs:

  releasedeploy:
    name: Deploy and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: '5.4'  # You can specify '5.1', '5.2', '5.3', '5.4', or 'luajit'

      - name: Set up Luarocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install Lua canvas library
        run: |
          git clone https://github.com/wspr/canvas-lms-lua
          cd canvas-lms-lua
          luarocks make

      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages

      - name: Make and deploy
        run: |
          echo "Deploying release ${{ github.ref_name }}"
          make upload
          zip -r release.zip _upload/
        env:
          CANVAS_API_TOKEN: ${{ secrets.CANVAS_API_TOKEN }}

      - name: Release
        uses: ghalactic/github-release-from-tag@v5

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
