name: Automated testing

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages
      - name: Run make
        run: make all
      - name: Archive documentation
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: |
            _build/*.pdf
          retention-days: 3
